### ISSUE TITLE
issue with getInstance?

### ISSUE THREAD

**Issue by yudelevi** [rochacon/elastic-nginx#6]
Looks like some incompatibility with ec2 instance pull (below are both scale up and down)

2015/02/09 19:34:34 Listening on 0.0.0.0:4444
2015/02/09 19:34:34 Monitoring events on topic: arn:aws:sns:us-east-1:redacted:prod-webapp-scale
2015/02/09 19:34:34 AWS Region: us-east-1
2015/02/09 19:34:34 Upstream 0: prod_webapp_scale
2015/02/09 19:34:34   ContainerFolder: /etc/nginx/upstream.d/scale
2015/02/09 19:34:34   File: /etc/nginx/upstream.d/prod_webapp_scale.upstreams
2015/02/09 19:35:27 Received Payload: {
  "Type" : "Notification",
  "MessageId" : "a355ffa9-f2f5-57ac-b383-b2fafcb7b183",
  "TopicArn" : "arn:aws:sns:us-east-1:redacted:aws_scale_prod",
  "Subject" : "Auto Scaling: launch for group \"prod-webapp-scale\"",
  "Message" : "{\"StatusCode\":\"InProgress\",\"Service\":\"AWS Auto Scaling\",\"AutoScalingGroupName\":\"prod-webapp-scale\",\"Description\":\"Launching a new EC2 instance: i-3d9bcecc\",\"ActivityId\":\"585980d3-9899-460f-a3c6-241e56d96efd\",\"Event\":\"autoscaling:EC2_INSTANCE_LAUNCH\",\"Details\":{\"Availability Zone\":\"us-east-1e\"},\"AutoScalingGroupARN\":\"scalegroup-redacted\",\"Progress\":50,\"Time\":\"2015-02-09T19:35:30.044Z\",\"AccountId\":\"1234\",\"RequestId\":\"585980d3-9899-460f-a3c6-241e56d96efd\",\"StatusMessage\":\"\",\"EndTime\":\"2015-02-09T19:35:30.044Z\",\"EC2InstanceId\":\"i-3d9bcecc\",\"StartTime\":\"2015-02-09T19:34:57.170Z\",\"Cause\":\"At 2015-02-09T19:34:51Z a user request executed policy Increase Group Size changing the desired capacity from 1 to 2.  At 2015-02-09T19:34:55Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 1 to 2.\"}",
  "Timestamp" : "2015-02-09T19:35:30.188Z",
  "SignatureVersion" : "1",
  "Signature" : "redacted",
  "SigningCertURL" : "https://sns.us-east-1.amazonaws.com/redacted.pem",
  "UnsubscribeURL" : "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:redacted"
}
2015/02/09 19:35:27 http: panic serving 54.239.98.166:22456: runtime error: invalid memory address or nil pointer dereference
goroutine 20 [running]:
net/http.funcÂ·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x6d95a0, 0x8bbb13)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
gopkg.in/amz.v1/ec2.(_EC2).query(0xc2080560c0, 0xc2080255c0, 0x633de0, 0xc2080255f0, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:146 +0x5af
gopkg.in/amz.v1/ec2.(_EC2).Instances(0xc2080560c0, 0x7f01b9d17228, 0x1, 0x1, 0x0, 0xc2080255f0, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:543 +0x10f
main.getInstance(0xc208038e36, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:126 +0x172
main.launch(0x7f01b9ed7bb0, 0xc208052460, 0x0, 0xc20804e630, 0x87, 0xc208024de0, 0x25, 0xc208040240, 0x3b, 0xc20800e580, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:235 +0x61
main.readMessage(0x7f01b9ed7bb0, 0xc208052460, 0xc208000820)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:215 +0xae5
net/http.HandlerFunc.ServeHTTP(0x7b09a0, 0x7f01b9ed7bb0, 0xc208052460, 0xc208000820)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(_ServeMux).ServeHTTP(0xc2080246c0, 0x7f01b9ed7bb0, 0xc208052460, 0xc208000820)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080043c0, 0x7f01b9ed7bb0, 0xc208052460, 0xc208000820)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(_conn).serve(0xc208050400)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(_Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
2015/02/09 19:35:58 Received Payload: {
  "Type" : "Notification",
  "MessageId" : "a355ffa9-f2f5-57ac-b383-b2fafcb7b183",
  "TopicArn" : "arn:aws:sns:us-east-1:redacted:aws_scale_prod",
  "Subject" : "Auto Scaling: launch for group \"prod-webapp-scale\"",
  "Message" : "{\"StatusCode\":\"InProgress\",\"Service\":\"AWS Auto Scaling\",\"AutoScalingGroupName\":\"prod-webapp-scale\",\"Description\":\"Launching a new EC2 instance: i-3d9bcecc\",\"ActivityId\":\"585980d3-9899-460f-a3c6-241e56d96efd\",\"Event\":\"autoscaling:EC2_INSTANCE_LAUNCH\",\"Details\":{\"Availability Zone\":\"us-east-1e\"},\"AutoScalingGroupARN\":\"scalegroup-redacted\",\"Progress\":50,\"Time\":\"2015-02-09T19:35:30.044Z\",\"AccountId\":\"1234\",\"RequestId\":\"585980d3-9899-460f-a3c6-241e56d96efd\",\"StatusMessage\":\"\",\"EndTime\":\"2015-02-09T19:35:30.044Z\",\"EC2InstanceId\":\"i-3d9bcecc\",\"StartTime\":\"2015-02-09T19:34:57.170Z\",\"Cause\":\"At 2015-02-09T19:34:51Z a user request executed policy Increase Group Size changing the desired capacity from 1 to 2.  At 2015-02-09T19:34:55Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 1 to 2.\"}",
  "Timestamp" : "2015-02-09T19:35:30.188Z",
  "SignatureVersion" : "1",
  "Signature" : "redacted",
  "SigningCertURL" : "https://sns.us-east-1.amazonaws.com/redacted.pem",
  "UnsubscribeURL" : "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:redacted"
}
2015/02/09 19:35:58 http: panic serving 54.239.98.225:1363: runtime error: invalid memory address or nil pointer dereference
goroutine 21 [running]:
net/http.funcÂ·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x6d95a0, 0x8bbb13)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
gopkg.in/amz.v1/ec2.(_EC2).query(0xc208056000, 0xc208025350, 0x633de0, 0xc208025380, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:146 +0x5af
gopkg.in/amz.v1/ec2.(_EC2).Instances(0xc208056000, 0x7f01b9d17228, 0x1, 0x1, 0x0, 0xc208025380, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:543 +0x10f
main.getInstance(0xc208038cd6, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:126 +0x172
main.launch(0x7f01b9ed7bb0, 0xc208052140, 0x0, 0xc20804e630, 0x87, 0xc208024de0, 0x25, 0xc208040240, 0x3b, 0xc20800e580, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:235 +0x61
main.readMessage(0x7f01b9ed7bb0, 0xc208052140, 0xc208000270)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:215 +0xae5
net/http.HandlerFunc.ServeHTTP(0x7b09a0, 0x7f01b9ed7bb0, 0xc208052140, 0xc208000270)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(_ServeMux).ServeHTTP(0xc2080246c0, 0x7f01b9ed7bb0, 0xc208052140, 0xc208000270)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080043c0, 0x7f01b9ed7bb0, 0xc208052140, 0xc208000270)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(_conn).serve(0xc208050300)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(_Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
2015/02/09 19:36:31 Received Payload: {
  "Type" : "Notification",
  "MessageId" : "a355ffa9-f2f5-57ac-b383-b2fafcb7b183",
  "TopicArn" : "arn:aws:sns:us-east-1:redacted:aws_scale_prod",
  "Subject" : "Auto Scaling: launch for group \"prod-webapp-scale\"",
  "Message" : "{\"StatusCode\":\"InProgress\",\"Service\":\"AWS Auto Scaling\",\"AutoScalingGroupName\":\"prod-webapp-scale\",\"Description\":\"Launching a new EC2 instance: i-3d9bcecc\",\"ActivityId\":\"585980d3-9899-460f-a3c6-241e56d96efd\",\"Event\":\"autoscaling:EC2_INSTANCE_LAUNCH\",\"Details\":{\"Availability Zone\":\"us-east-1e\"},\"AutoScalingGroupARN\":\"scalegroup-redacted\",\"Progress\":50,\"Time\":\"2015-02-09T19:35:30.044Z\",\"AccountId\":\"1234\",\"RequestId\":\"585980d3-9899-460f-a3c6-241e56d96efd\",\"StatusMessage\":\"\",\"EndTime\":\"2015-02-09T19:35:30.044Z\",\"EC2InstanceId\":\"i-3d9bcecc\",\"StartTime\":\"2015-02-09T19:34:57.170Z\",\"Cause\":\"At 2015-02-09T19:34:51Z a user request executed policy Increase Group Size changing the desired capacity from 1 to 2.  At 2015-02-09T19:34:55Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 1 to 2.\"}",
  "Timestamp" : "2015-02-09T19:35:30.188Z",
  "SignatureVersion" : "1",
  "Signature" : "reda",
  "SigningCertURL" : "https://sns.us-east-1.amazonaws.com/redacted.pem",
  "UnsubscribeURL" : "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:redacted"
}
2015/02/09 19:36:31 http: panic serving 54.239.98.225:24888: runtime error: invalid memory address or nil pointer dereference
goroutine 22 [running]:
net/http.funcÂ·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x6d95a0, 0x8bbb13)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
gopkg.in/amz.v1/ec2.(_EC2).query(0xc208056180, 0xc208025950, 0x633de0, 0xc208025980, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:146 +0x5af
gopkg.in/amz.v1/ec2.(_EC2).Instances(0xc208056180, 0x7f01b9d17228, 0x1, 0x1, 0x0, 0xc208025980, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:543 +0x10f
main.getInstance(0xc2080390c6, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:126 +0x172
main.launch(0x7f01b9ed7bb0, 0xc208052640, 0x0, 0xc20804e630, 0x87, 0xc208024de0, 0x25, 0xc208040240, 0x3b, 0xc20800e580, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:235 +0x61
main.readMessage(0x7f01b9ed7bb0, 0xc208052640, 0xc208000a90)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:215 +0xae5
net/http.HandlerFunc.ServeHTTP(0x7b09a0, 0x7f01b9ed7bb0, 0xc208052640, 0xc208000a90)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(_ServeMux).ServeHTTP(0xc2080246c0, 0x7f01b9ed7bb0, 0xc208052640, 0xc208000a90)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080043c0, 0x7f01b9ed7bb0, 0xc208052640, 0xc208000a90)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(_conn).serve(0xc208050480)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(_Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
2015/02/09 19:36:55 Received Payload: {
  "Type" : "Notification",
  "MessageId" : "a355ffa9-f2f5-57ac-b383-b2fafcb7b183",
  "TopicArn" : "arn:aws:sns:us-east-1:redacted:aws_scale_prod",
  "Subject" : "Auto Scaling: launch for group \"prod-webapp-scale\"",
  "Message" : "{\"StatusCode\":\"InProgress\",\"Service\":\"AWS Auto Scaling\",\"AutoScalingGroupName\":\"prod-webapp-scale\",\"Description\":\"Launching a new EC2 instance: i-3d9bcecc\",\"ActivityId\":\"585980d3-9899-460f-a3c6-241e56d96efd\",\"Event\":\"autoscaling:EC2_INSTANCE_LAUNCH\",\"Details\":{\"Availability Zone\":\"us-east-1e\"},\"AutoScalingGroupARN\":\"scalegroup-redacted\",\"Progress\":50,\"Time\":\"2015-02-09T19:35:30.044Z\",\"AccountId\":\"1234\",\"RequestId\":\"585980d3-9899-460f-a3c6-241e56d96efd\",\"StatusMessage\":\"\",\"EndTime\":\"2015-02-09T19:35:30.044Z\",\"EC2InstanceId\":\"i-3d9bcecc\",\"StartTime\":\"2015-02-09T19:34:57.170Z\",\"Cause\":\"At 2015-02-09T19:34:51Z a user request executed policy Increase Group Size changing the desired capacity from 1 to 2.  At 2015-02-09T19:34:55Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 1 to 2.\"}",
  "Timestamp" : "2015-02-09T19:35:30.188Z",
  "SignatureVersion" : "1",
  "Signature" : "redacted",
  "SigningCertURL" : "https://sns.us-east-1.amazonaws.com/redacted.pem",
  "UnsubscribeURL" : "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:redacted"
}
2015/02/09 19:36:55 http: panic serving 54.239.98.33:56379: runtime error: invalid memory address or nil pointer dereference
goroutine 23 [running]:
net/http.funcÂ·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x6d95a0, 0x8bbb13)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
gopkg.in/amz.v1/ec2.(_EC2).query(0xc208056000, 0xc208025080, 0x633de0, 0xc2080250b0, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:146 +0x5af
gopkg.in/amz.v1/ec2.(_EC2).Instances(0xc208056000, 0x7f01b9d17228, 0x1, 0x1, 0x0, 0xc2080250b0, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:543 +0x10f
main.getInstance(0xc208038ae0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:126 +0x172
main.launch(0x7f01b9ed7bb0, 0xc208052820, 0x0, 0xc20804e630, 0x87, 0xc208024de0, 0x25, 0xc208040240, 0x3b, 0xc20800e580, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:235 +0x61
main.readMessage(0x7f01b9ed7bb0, 0xc208052820, 0xc208001380)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:215 +0xae5
net/http.HandlerFunc.ServeHTTP(0x7b09a0, 0x7f01b9ed7bb0, 0xc208052820, 0xc208001380)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(_ServeMux).ServeHTTP(0xc2080246c0, 0x7f01b9ed7bb0, 0xc208052820, 0xc208001380)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080043c0, 0x7f01b9ed7bb0, 0xc208052820, 0xc208001380)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(_conn).serve(0xc208050580)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(_Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
2015/02/09 19:37:07 Received Payload: {
  "Type" : "Notification",
  "MessageId" : "6a95e502-961e-5e1f-a46d-a85198b84a93",
  "TopicArn" : "arn:aws:sns:us-east-1:redacted:aws_scale_prod",
  "Subject" : "Auto Scaling: termination for group \"prod-webapp-scale\"",
  "Message" : "{\"StatusCode\":\"InProgress\",\"Service\":\"AWS Auto Scaling\",\"AutoScalingGroupName\":\"prod-webapp-scale\",\"Description\":\"Terminating EC2 instance: i-3d9bcecc\",\"ActivityId\":\"344f5ce7-8c02-4763-b431-df4cdaa5bb71\",\"Event\":\"autoscaling:EC2_INSTANCE_TERMINATE\",\"Details\":{\"Availability Zone\":\"us-east-1e\"},\"AutoScalingGroupARN\":\"scalegroup-redacted\",\"Progress\":50,\"Time\":\"2015-02-09T19:37:10.111Z\",\"AccountId\":\"1234\",\"RequestId\":\"344f5ce7-8c02-4763-b431-df4cdaa5bb71\",\"StatusMessage\":\"\",\"EndTime\":\"2015-02-09T19:37:10.111Z\",\"EC2InstanceId\":\"i-3d9bcecc\",\"StartTime\":\"2015-02-09T19:36:26.423Z\",\"Cause\":\"At 2015-02-09T19:36:23Z a user request executed policy Decrease Group Size changing the desired capacity from 2 to 1.  At 2015-02-09T19:36:26Z an instance was taken out of service in response to a difference between desired and actual capacity, shrinking the capacity from 2 to 1.  At 2015-02-09T19:36:26Z instance i-3d9bcecc was selected for termination.\"}",
  "Timestamp" : "2015-02-09T19:37:10.607Z",
  "SignatureVersion" : "1",
  "Signature" : "sign-redacted=",
  "SigningCertURL" : "https://sns.us-east-1.amazonaws.com/redacted.pem",
  "UnsubscribeURL" : "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:redacted"
}
2015/02/09 19:37:07 http: panic serving 54.239.98.163:54187: runtime error: invalid memory address or nil pointer dereference
goroutine 24 [running]:
net/http.funcÂ·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x6d95a0, 0x8bbb13)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
gopkg.in/amz.v1/ec2.(_EC2).query(0xc2080560c0, 0xc2080256b0, 0x633de0, 0xc2080256e0, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:146 +0x5af
gopkg.in/amz.v1/ec2.(_EC2).Instances(0xc2080560c0, 0x7f01b9d17228, 0x1, 0x1, 0x0, 0xc2080256e0, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:543 +0x10f
main.getInstance(0xc208038f66, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:126 +0x172
main.terminate(0x7f01b9ed7bb0, 0xc208052320, 0x0, 0xc20804e630, 0x87, 0xc208024de0, 0x25, 0xc208040240, 0x3b, 0xc20800e580, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:264 +0x61
main.readMessage(0x7f01b9ed7bb0, 0xc208052320, 0xc208000340)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:217 +0xb80
net/http.HandlerFunc.ServeHTTP(0x7b09a0, 0x7f01b9ed7bb0, 0xc208052320, 0xc208000340)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(_ServeMux).ServeHTTP(0xc2080246c0, 0x7f01b9ed7bb0, 0xc208052320, 0xc208000340)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080043c0, 0x7f01b9ed7bb0, 0xc208052320, 0xc208000340)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(_conn).serve(0xc208050300)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(_Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313
2015/02/09 19:37:31 Received Payload: {
  "Type" : "Notification",
  "MessageId" : "6a95e502-961e-5e1f-a46d-a85198b84a93",
  "TopicArn" : "arn:aws:sns:us-east-1:redacted:aws_scale_prod",
  "Subject" : "Auto Scaling: termination for group \"prod-webapp-scale\"",
  "Message" : "{\"StatusCode\":\"InProgress\",\"Service\":\"AWS Auto Scaling\",\"AutoScalingGroupName\":\"prod-webapp-scale\",\"Description\":\"Terminating EC2 instance: i-3d9bcecc\",\"ActivityId\":\"344f5ce7-8c02-4763-b431-df4cdaa5bb71\",\"Event\":\"autoscaling:EC2_INSTANCE_TERMINATE\",\"Details\":{\"Availability Zone\":\"us-east-1e\"},\"AutoScalingGroupARN\":\"scalegroup-redacted\",\"Progress\":50,\"Time\":\"2015-02-09T19:37:10.111Z\",\"AccountId\":\"1234\",\"RequestId\":\"344f5ce7-8c02-4763-b431-df4cdaa5bb71\",\"StatusMessage\":\"\",\"EndTime\":\"2015-02-09T19:37:10.111Z\",\"EC2InstanceId\":\"i-3d9bcecc\",\"StartTime\":\"2015-02-09T19:36:26.423Z\",\"Cause\":\"At 2015-02-09T19:36:23Z a user request executed policy Decrease Group Size changing the desired capacity from 2 to 1.  At 2015-02-09T19:36:26Z an instance was taken out of service in response to a difference between desired and actual capacity, shrinking the capacity from 2 to 1.  At 2015-02-09T19:36:26Z instance i-3d9bcecc was selected for termination.\"}",
  "Timestamp" : "2015-02-09T19:37:10.607Z",
  "SignatureVersion" : "1",
  "Signature" :redacted",
  "SigningCertURL" : "https://sns.us-east-1.amazonaws.com/redacted.pem",
  "UnsubscribeURL" : "https://sns.us-east-1.amazonaws.com/?Action=Unsubscribe&SubscriptionArn=arn:aws:sns:us-east-1:redacted"
}
2015/02/09 19:37:31 http: panic serving 54.239.98.165:65060: runtime error: invalid memory address or nil pointer dereference
goroutine 25 [running]:
net/http.funcÂ·011()
        /usr/lib/go/src/pkg/net/http/server.go:1100 +0xb7
runtime.panic(0x6d95a0, 0x8bbb13)
        /usr/lib/go/src/pkg/runtime/panic.c:248 +0x18d
gopkg.in/amz.v1/ec2.(_EC2).query(0xc208056180, 0xc208025e00, 0x633de0, 0xc208025e30, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:146 +0x5af
gopkg.in/amz.v1/ec2.(_EC2).Instances(0xc208056180, 0x7f01b9d17228, 0x1, 0x1, 0x0, 0xc208025e30, 0x0, 0x0)
        /opt/golang/src/gopkg.in/amz.v1/ec2/ec2.go:543 +0x10f
main.getInstance(0xc2080393b6, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:126 +0x172
main.terminate(0x7f01b9ed7bb0, 0xc2080525a0, 0x0, 0xc20804e630, 0x87, 0xc208024de0, 0x25, 0xc208040240, 0x3b, 0xc20800e580, ...)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:264 +0x61
main.readMessage(0x7f01b9ed7bb0, 0xc2080525a0, 0xc208000a90)
        /opt/golang/src/github.com/rochacon/elastic-nginx/elnginx.go:217 +0xb80
net/http.HandlerFunc.ServeHTTP(0x7b09a0, 0x7f01b9ed7bb0, 0xc2080525a0, 0xc208000a90)
        /usr/lib/go/src/pkg/net/http/server.go:1235 +0x40
net/http.(_ServeMux).ServeHTTP(0xc2080246c0, 0x7f01b9ed7bb0, 0xc2080525a0, 0xc208000a90)
        /usr/lib/go/src/pkg/net/http/server.go:1511 +0x1a3
net/http.serverHandler.ServeHTTP(0xc2080043c0, 0x7f01b9ed7bb0, 0xc2080525a0, 0xc208000a90)
        /usr/lib/go/src/pkg/net/http/server.go:1673 +0x19f
net/http.(_conn).serve(0xc208050400)
        /usr/lib/go/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(_Server).Serve
        /usr/lib/go/src/pkg/net/http/server.go:1721 +0x313

**Comment by rochacon** [comment]
Hey @yudelevi! I've seen some similar errors, the problem was due to some new version of goamz. Did you built it from source? If yes, may you please check your gopkg.in/amz.v1 revision?

I'll look into freezing/vendoring those dependencies with Godep.

**Comment by rochacon** [comment]
@yudelevi found it. :smile:
